spring:
  cloud:
    gateway:
      routes:
        - id: eureka-client-provider #路由的ID
          uri: lb://eureka-client-provider
          predicates:
            - Path=/provider/** # 路由规则
            - name: ReadBodyPredicateFactory #读取body断言
              args:
                inClass: "#{T(String)}" #body数据类型
                predicate: "#{@testRequestBody}" #自定义断言处理器
            # 当且仅当请求时的时间After配置的时间时，才会转发到用户微服务
            # 目前配置不会进该路由配置，所以返回404
            # 将时间改成 < now的时间，则访问http://localhost:9100/** -> eureka-client-provider/**
            # 访问http://localhost:9100/provider/demo/hello-> eureka-client-provider/demo/hello
            #- After=2020-07-01T23:33:00.000+08:00[Asia/Shanghai]
            # 当且仅当请求时的时间Before配置的时间时，才会转发到用户微服务
            # 目前配置不会进该路由配置，所以返回404
            # 将时间改成 > now的时间，则访问http://localhost:9100/** -> eureka-client-provider/**
            # 访问http://localhost:9100/provider/demo/hello -> eureka-client-provider/demo/hello
            #- Before=2021-07-01T23:33:00.000+08:00[Asia/Shanghai]
            # 当且仅当请求时的时间Between配置的时间时，才会转发到用户微服务
            # 因此，访问http://localhost:9100/** -> eureka-client-provider/**
            # 访问http://localhost:9100/provider/demo/hello -> eureka-client-provider/demo/hello
            #- Between=2020-07-01T13:30:00+08:00[Asia/Shanghai], 2020-07-02T18:30:00+08:00[Asia/Shanghai]
            # 当且仅当带有名为somecookie，并且值符合正则ch.p的Cookie时，才会转发到用户微服务
            # 如Cookie满足条件，则访问http://localhost:9100/** -> eureka-client-provider/**
            # 访问http://localhost:9100/provider/demo/hello -> eureka-client-provider/demo/hello
            #- Cookie=username,tom
            # 当且仅当带有名为X-Request-Id，并且值符合正则\d+的Header时，才会转发到用户微服务
            # 如Header满足条件，则访问http://localhost:9100/** -> eureka-client-provider/**
            # 访问http://localhost:9100/provider/demo/hello -> eureka-client-provider/demo/hello
            #- Header=X-Request-Id, \d+
            # 当且仅当名为Host的Header符合**.hxmec.com或者**.heisea.cn时，才会转发用户微服务
            # 如Host满足条件，则访问http://localhost:9100/** -> eureka-client-provider/**
            # 访问http://localhost:9100/provider/demo/hello -> eureka-client-provider/demo/hello
            #- Host=**.hxmec.com,**.heisea.cn
            # 当且仅当HTTP请求方法是GET时，才会转发用户微服务
            # 如请求方法满足条件，则访问http://localhost:9100/** -> eureka-client-provider/**
            # 访问http://localhost:9100/provider/demo/hello -> eureka-client-provider/demo/hello
            #- Method=GET
            # 当且仅当请求带有name的参数，才会转发到用户微服务
            # 访问http://localhost:9100/provider/demo/feign?name=xx -> eureka-client-provider的/demo/feign
            #- Query=name
            # 当且仅当请求IP是192.168.29.1/24网段，例如192.168.29.188，才会转发到用户微服务
            # 问http://localhost:9100/provider/demo/hello -> eureka-client-provider/demo/hello
            #- RemoteAddr=192.168.29.1/24
          filters:
            - StripPrefix=1