server:
  port: 20001
# Spring
spring:
  application:
    name: test1-server
  datasource:
    url: jdbc:mysql://192.168.121.134:3306/spring_cloud?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
#    primary:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/media?useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: 123qwe
#    secondary:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: 123qwe
  jpa:
    database: MYSQL
    show-sql: true
#    hibernate:
#      #配置自动建表`：updata:没有表新建，有表更新操作,控制台显示建表语句
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  druid:
    initial-size: 2
    max-active: 15
    min-idle: 2
    max-wait: 1234
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 5
    validation-query: select 1 from dual
    validation-query-timeout: 1
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 10000
    min-evictable-idle-time-millis: 30001
    async-close-connection-enable: true
    servlet:
      allow: 127.0.0.1
      deny: none
      loginUsername: root
      loginPassword: root123
      resetEnable: false
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka #这里的port与eureka的端口对应
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
test1_server:
  test:
    value0: fuck you!