zuul:
  #配置统一访问前缀
  #prefix: /zuul
  #配置过滤敏感的请求头信息，设置为空就不会过滤
  #sensitive-headers: Cookie,Set-Cookie,Authorization
  #设置为true重定向是会添加host请求头
  #add-host-header: true
  #关闭默认路由配置
  ignored-services: eureka-client-provider,eureka-client-consumer
  routes: #给服务配置路由
    eureka-client-provider:
      path: /provider/**
    eureka-client-consumer:
      path: /consumer/**

#路由的端点
management:
  endpoints:
    web:
      exposure:
        include: 'routes'