server:
  port: 9001
spring:
  application:
    name: eureka-client-provider
  zipkin:
    base-url: http://localhost:9411
    #设置Sleuth的抽样收集概率
  sleuth:
    sampler:
      probability: 0.1

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/