server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: test1_route
        uri: http://localhost:20001
        predicates:
        - Path=/route1/**
        filters:
        - RewritePath=/route1/(?<remaining>.*), /${remaining}
      - id: test2_route
        uri: lb://TEST2-SERVER
        predicates:
        - Path=/route2/**
        filters:
        - RewritePath=/route2/(?<remaining>.*), /${remaining}
      discovery:
        locator:
          enabled: true
      loadbalancer:
        use404: true
management:
  endpoints:
    web:
      exposure:
        include: gateway,refresh,health,info
    gateway:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka #这里的port与eureka的端口对应
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}